defaults: &defaults
  docker:
  - image: golang:1.11.0
  working_directory: /app

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
    - checkout
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /app

  check-dependencies:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}

  lint:
    <<: *defaults
    docker:
    - image: quay.io/kubermatic/gometalinter:latest
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make lint

  test:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make test

  build:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make build
    - save_cache:
        key: terraform-docs-{{ .Revision }}
        paths:
        - /app

workflows:
  version: 2
  build:
    jobs:
    - checkout_code:
        filters:
          tags:
            only: /v.*/
    - check-dependencies:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
    - lint:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
    - test:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
    - build:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
